const MONGO_CONNECTION_STRING = 'mongodb://localhost:27020'
const ELASTIC_CONNECTION_STRING = 'localhost:9200'
const SERVER_PORT = 9000

const ELASTIC_CONFIG = {
  pagesIndex: 'pages',
  pagesType: 'page'
}

module.exports = {
  MONGO_CONNECTION_STRING: MONGO_CONNECTION_STRING,
  ELASTIC_CONNECTION_STRING: ELASTIC_CONNECTION_STRING,
  ELASTIC_CONFIG,
  SERVER_PORT: SERVER_PORT
}