FROM python:3-slim

ADD app.py /

# Set the working directory
WORKDIR /usr/src/app/

# Copy the current directory contents into the container
COPY . /usr/src/app/

# Install any needed packages specified in requirements.txt
RUN pip install requests requests[socks] bs4 pysocks

# Run app.py when the container launches
CMD ["python", "app.py"]